### ISSUE TITLE
Trying to contact you to invite you to attend the rust-libp2p maintainers call

### ISSUE THREAD

**Issue by dhuseby** [dariusc93/rust-libp2p#2]
### Summary

Hello @dariusc93 

During the last rust-libp2p maintainers call several people (@jxs and others) requested that I reach out to you and invite you to attend the next rust-libp2p maintainers call: https://lu.ma/2024-06-04-rust-libp2p

We have quite a lot of technical coordination and planning happening at each meeting as you can see from the minutes from past meetings: https://docs.google.com/document/d/1bMfzeOPGwEGAet-y_uy2DL_Yxgceu7PhkPuTrpMA2oc/edit?usp=sharing

If you have any questions, please feel free to find me on Filecoin Slack, Discord, or Telegram in the libp2p communities there. You can get the links to those chat platforms from the https://libp2p.io homepage.

I hope you can attend a future meeting.

Cheers! 🍻
Dave 

### Expected behavior

That you'll attend a future meeting : )

### Actual behavior

You haven't attended any so far ; )

### Would you like to work on fixing this bug ?

Yes

**Comment by dhuseby** [comment]
I'd also like to get @drHuangMHT to attend as well.

**Comment by drHuangMHT** [comment]
Thank you @dhuseby, that would be 10 p.m. next Tuesday in my locale(UTC+8, China) according to the calendar. I'll try to make it happen but I should mention that I'm currently living in a dorm with some noisy roommates who often shout out loud when playing games. Also my oral English is not that good so I could end up typing instead :)

**Comment by dhuseby** [comment]
> Thank you @dhuseby, that would be 10 p.m. next Tuesday in my locale(UTC+8, China) according to the calendar. I'll try to make it happen but I should mention that I'm currently living in a dorm with some noisy roommates who often shout out loud when playing games. Also my oral English is not that good so I could end up typing instead :)

That would be excellent!! We will be happy to have you. I have kids that play video games the same way. I look forward to meeting you. Typed communication is perfectly fine. We also have active chats on Slack, Discord, and Telegram. The links are on the libp2p.io homepage.


https://github.com/dariusc93/rust-libp2p/assets/5017470/8e7b13ec-d118-4234-94e2-44570be5a9cc

**Comment by dariusc93** [comment]
Hey @dhuseby. I did shoot you a message on discord but I will also respond here. I will try to do my best to make it to the next meeting but cannot make any promises. I should be able to work it in since the time is doable :)
